#!/usr/bin/env python3
from __future__ import annotations

import argparse
import functools
import hashlib
import json
import os
import re
import urllib.parse
import urllib.request
from dataclasses import dataclass
from pathlib import Path


EXACT_REQUIREMENT_RE = re.compile(
    r"^(?P<name>[A-Za-z0-9_.-]+)==(?P<version>[^;\s]+)(?P<marker>\s*;\s*.+)?$"
)
SHA256_RE = re.compile(r"^[0-9a-f]{64}$")
REPO_ROOT = Path(__file__).resolve().parents[2]


@dataclass(frozen=True)
class LockSpec:
    source: Path
    destination: Path


LOCK_SPECS = (
    LockSpec(
        REPO_ROOT / "backend" / "requirements-bootstrap.in",
        REPO_ROOT / "backend" / "requirements-bootstrap.lock",
    ),
    LockSpec(
        REPO_ROOT / "backend" / "requirements-macos-x64-build.in",
        REPO_ROOT / "backend" / "requirements-macos-x64-build.lock",
    ),
    LockSpec(
        REPO_ROOT / "backend" / "requirements-runtime.in",
        REPO_ROOT / "backend" / "requirements.lock",
    ),
    LockSpec(
        REPO_ROOT / "backend" / "requirements-dev.in",
        REPO_ROOT / "backend" / "requirements-dev.lock",
    ),
    LockSpec(
        REPO_ROOT / "backend" / "requirements-audit.in",
        REPO_ROOT / "backend" / "requirements-audit.lock",
    ),
    LockSpec(
        REPO_ROOT / "scripts" / "desktop_visible_auth_requirements.txt",
        REPO_ROOT / "scripts" / "desktop_visible_auth_requirements.lock",
    ),
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Regenerate every cross-platform Python lock from its committed exact input."
        )
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify generated content without writing lock files.",
    )
    return parser.parse_args()


def requirement_lines(path: Path) -> list[str]:
    logical_lines: list[str] = []
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or line.startswith("--hash="):
            continue
        if line.endswith("\\"):
            line = line[:-1].rstrip()
        if line:
            logical_lines.append(line)
    return logical_lines


@functools.lru_cache(maxsize=None)
def release_hashes(name: str, version: str) -> tuple[str, ...]:
    project = urllib.parse.quote(name, safe="")
    release = urllib.parse.quote(version, safe="")
    request = urllib.request.Request(
        f"https://pypi.org/pypi/{project}/{release}/json",
        headers={"User-Agent": "BreakTwenty hash-lock generator"},
    )
    with urllib.request.urlopen(request, timeout=30) as response:
        payload = json.load(response)
    hashes = {
        str(item.get("digests", {}).get("sha256") or "").lower()
        for item in payload.get("urls") or []
    }
    if not hashes or any(not SHA256_RE.fullmatch(value) for value in hashes):
        raise RuntimeError(f"PyPI returned invalid SHA-256 metadata for {name}=={version}")
    return tuple(sorted(hashes))


def _translated_lines(spec: LockSpec) -> list[str]:
    source_to_destination = {
        candidate.source.resolve(): candidate.destination.resolve()
        for candidate in LOCK_SPECS
    }
    translated: list[str] = []
    for line in requirement_lines(spec.source):
        if not line.startswith(("-r ", "--requirement ")):
            translated.append(line)
            continue
        include = line.split(maxsplit=1)[1]
        include_source = (spec.source.parent / include).resolve()
        include_destination = source_to_destination.get(include_source)
        if include_destination is None:
            raise RuntimeError(
                f"Lock input {spec.source} includes unmanaged source {include}"
            )
        relative = os.path.relpath(include_destination, spec.destination.parent)
        translated.append(f"-r {Path(relative).as_posix()}")
    return translated


def render_lock(spec: LockSpec) -> str:
    source_label = spec.source.relative_to(REPO_ROOT).as_posix()
    rendered = [
        "# Generated by backend/scripts/generate_python_hash_lock.py.",
        f"# Exact input: {source_label}",
        "# Regenerate all locks: python3 backend/scripts/generate_python_hash_lock.py",
        "# SHA-256 values cover every PyPI artifact published for each exact version",
        "# for supported Python 3.12 Linux x64, Windows x64, and macOS arm64/x64 runtimes.",
    ]
    for line in _translated_lines(spec):
        if line.startswith(("-r ", "--requirement ")):
            rendered.append(line)
            continue
        match = EXACT_REQUIREMENT_RE.fullmatch(line)
        if not match:
            raise RuntimeError(f"Requirement is not an exact PyPI pin: {line}")
        hashes = release_hashes(match.group("name"), match.group("version"))
        rendered.append(f"{line} \\")
        for index, digest in enumerate(hashes):
            suffix = " \\" if index < len(hashes) - 1 else ""
            rendered.append(f"    --hash=sha256:{digest}{suffix}")
    rendered.append("")
    return "\n".join(rendered)


def main() -> int:
    args = parse_args()
    generated = {spec: render_lock(spec) for spec in LOCK_SPECS}
    if args.check:
        stale = [
            spec.destination
            for spec, content in generated.items()
            if not spec.destination.is_file()
            or spec.destination.read_text(encoding="utf-8") != content
        ]
        if stale:
            for destination in stale:
                print(f"Stale lock: {destination.relative_to(REPO_ROOT)}")
            return 1
        print("All Python dependency locks are current.")
        return 0
    for spec, content in generated.items():
        spec.destination.parent.mkdir(parents=True, exist_ok=True)
        spec.destination.write_text(content, encoding="utf-8")
        digest = hashlib.sha256(content.encode("utf-8")).hexdigest()
        print(
            f"Wrote {spec.destination.relative_to(REPO_ROOT)} "
            f"from {spec.source.relative_to(REPO_ROOT)} ({digest})"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
