"""initial public schema

Revision ID: 0001
Revises: 
Create Date: 2026-08-03 02:39:18.804121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benchmark_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('close', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'symbol', 'date', name='uq_benchmark_prices_provider_symbol_date')
    )
    with op.batch_alter_table('benchmark_prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_benchmark_prices_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_benchmark_prices_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_benchmark_prices_symbol'), ['symbol'], unique=False)

    op.create_table('fx_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('cad_per_unit', sa.Numeric(precision=30, scale=12), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('cad_per_unit > 0', name='ck_fx_rates_cad_per_unit_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'currency', name='uq_fx_rates_date_currency')
    )
    with op.batch_alter_table('fx_rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fx_rates_currency'), ['currency'], unique=False)
        batch_op.create_index(batch_op.f('ix_fx_rates_date'), ['date'], unique=False)

    op.create_table('symbol_names',
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('provider', 'identifier')
    )
    op.create_table('symbol_sectors',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('instrument_kind', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('icon_set', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('classification', sa.String(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('seed_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('parent_id IS NULL OR parent_id <> id', name='ck_categories_parent_not_self'),
    sa.ForeignKeyConstraint(['parent_id', 'user_id'], ['categories.id', 'categories.user_id'], name='fk_categories_parent_owner', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'user_id', name='uq_categories_id_user_id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_seed_key'), ['seed_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_user_id'), ['user_id'], unique=False)

    op.create_table('institutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.Column('sync_status', sa.String(), nullable=False),
    sa.Column('logo', sa.LargeBinary(), nullable=True),
    sa.Column('logo_mime', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('cash_tracking_start', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'user_id', name='uq_institutions_id_user_id')
    )
    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_institutions_user_id'), ['user_id'], unique=False)
    op.create_index(
        'uq_institutions_user_synced_provider',
        'institutions',
        ['user_id', 'provider'],
        unique=True,
        sqlite_where=sa.text("type IN ('api', 'scraper')"),
        postgresql_where=sa.text("type IN ('api', 'scraper')"),
    )

    op.create_table('market_strip_snapshot_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('symbol_key', sa.String(), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('sample_slot', sa.String(), nullable=False),
    sa.Column('close', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', 'source', 'mode', 'symbol_key', 'local_date', 'sample_slot', name='uq_market_strip_snapshot_points_sample')
    )
    with op.batch_alter_table('market_strip_snapshot_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_strip_snapshot_points_local_date'), ['local_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_strip_snapshot_points_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_strip_snapshot_points_symbol_key'), ['symbol_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_strip_snapshot_points_user_id'), ['user_id'], unique=False)

    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'key', name='uq_settings_user_id_key')
    )
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settings_user_id'), ['user_id'], unique=False)

    op.create_table('user_secret_artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('secret_kind', sa.String(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'secret_kind', name='uq_user_secret_artifacts_user_id_secret_kind')
    )
    with op.batch_alter_table('user_secret_artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_secret_artifacts_user_id'), ['user_id'], unique=False)

    op.create_table('visible_auth_attempt_artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('attempt_id', sa.String(), nullable=False),
    sa.Column('artifact_kind', sa.String(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', 'attempt_id', 'artifact_kind', name='uq_visible_auth_attempt_artifacts_user_provider_attempt_kind')
    )
    with op.batch_alter_table('visible_auth_attempt_artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visible_auth_attempt_artifacts_attempt_id'), ['attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visible_auth_attempt_artifacts_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_visible_auth_attempt_artifacts_user_id'), ['user_id'], unique=False)

    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('account_type', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('is_liability', sa.Boolean(), nullable=False),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_imported', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_synced', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opening_balance', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('opening_balance_date', sa.Date(), nullable=True),
    sa.Column('purchase_value', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('secured_asset_account_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('secured_asset_account_id IS NULL OR secured_asset_account_id <> id', name='ck_accounts_secured_asset_not_self'),
    sa.ForeignKeyConstraint(['institution_id', 'user_id'], ['institutions.id', 'institutions.user_id'], name='fk_accounts_institution_owner', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['secured_asset_account_id', 'user_id'], ['accounts.id', 'accounts.user_id'], name='fk_accounts_secured_asset_owner', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'institution_id', 'user_id', name='uq_accounts_id_institution_id_user_id'),
    sa.UniqueConstraint('id', 'user_id', name='uq_accounts_id_user_id'),
    sa.UniqueConstraint('user_id', 'institution_id', 'external_id', name='uq_accounts_user_id_institution_id_external_id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_secured_asset_account_id'), ['secured_asset_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_user_id'), ['user_id'], unique=False)

    op.create_table('category_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description_pattern', sa.String(), nullable=False),
    sa.Column('is_regex', sa.Boolean(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('account_type', sa.String(), nullable=True),
    sa.Column('amount_sign', sa.String(), nullable=True),
    sa.Column('transaction_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category_id', 'user_id'], ['categories.id', 'categories.user_id'], name='fk_category_rules_category_owner', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('category_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_rules_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_category_rules_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_category_rules_user_id'), ['user_id'], unique=False)

    op.create_table('connection_auth_artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('artifact_kind', sa.String(), nullable=False),
    sa.Column('slot', sa.String(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['institution_id', 'user_id'], ['institutions.id', 'institutions.user_id'], name='fk_connection_auth_artifacts_connection_owner', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'institution_id', 'artifact_kind', 'slot', name='uq_connection_auth_artifacts_user_id_institution_id_artifact_kind_slot')
    )
    with op.batch_alter_table('connection_auth_artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_connection_auth_artifacts_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_connection_auth_artifacts_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_connection_auth_artifacts_user_id'), ['user_id'], unique=False)

    op.create_table('recurring_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('merchant_key', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('cadence', sa.String(), nullable=False),
    sa.Column('interval_days', sa.Float(), nullable=True),
    sa.Column('avg_amount', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('amount_min', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('amount_max', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('last_seen_date', sa.Date(), nullable=True),
    sa.Column('next_expected_date', sa.Date(), nullable=True),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount_min IS NULL OR amount_max IS NULL OR amount_min <= amount_max', name='ck_recurring_series_amount_range'),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_recurring_series_confidence'),
    sa.CheckConstraint('occurrence_count >= 0', name='ck_recurring_series_occurrence_count'),
    sa.ForeignKeyConstraint(['category_id', 'user_id'], ['categories.id', 'categories.user_id'], name='fk_recurring_series_category_owner'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'user_id', name='uq_recurring_series_id_user_id'),
    sa.UniqueConstraint('user_id', 'merchant_key', 'direction', name='uq_recurring_series_user_merchant_direction')
    )
    with op.batch_alter_table('recurring_series', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recurring_series_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recurring_series_merchant_key'), ['merchant_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_recurring_series_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_recurring_series_user_id'), ['user_id'], unique=False)

    op.create_table('transaction_import_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('sync_id', sa.String(), nullable=True),
    sa.Column('source_sync_id', sa.String(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_progress_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_progress_label', sa.String(), nullable=True),
    sa.Column('stale_recovery_count', sa.Integer(), nullable=False),
    sa.Column('lease_token', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('stale_recovery_count >= 0', name='ck_transaction_import_jobs_stale_recovery_count'),
    sa.ForeignKeyConstraint(['institution_id', 'user_id'], ['institutions.id', 'institutions.user_id'], name='fk_transaction_import_jobs_connection_owner', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', name='uq_transaction_import_jobs_job_id')
    )
    with op.batch_alter_table('transaction_import_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_import_jobs_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_import_jobs_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_import_jobs_last_progress_at'), ['last_progress_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_import_jobs_lease_token'), ['lease_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_import_jobs_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_import_jobs_source_sync_id'), ['source_sync_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_import_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_import_jobs_sync_id'), ['sync_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_import_jobs_user_id'), ['user_id'], unique=False)

    op.create_table('balance_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['account_id', 'user_id'], ['accounts.id', 'accounts.user_id'], name='fk_balance_history_account_owner', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'date', name='uq_balance_history_account_date')
    )
    with op.batch_alter_table('balance_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_balance_history_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_balance_history_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_balance_history_user_id'), ['user_id'], unique=False)

    op.create_table('holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=30, scale=12), nullable=False),
    sa.Column('market_value', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('average_cost', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('last_price', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('contract_multiplier', sa.Numeric(precision=30, scale=12), nullable=True),
    sa.Column('change_pct', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('daily_pnl', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id', 'user_id'], ['accounts.id', 'accounts.user_id'], name='fk_holdings_account_owner', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'symbol', name='uq_holdings_account_symbol')
    )
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_holdings_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_holdings_user_id'), ['user_id'], unique=False)

    op.create_table('transaction_import_account_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('account_external_id', sa.String(), nullable=False),
    sa.Column('account_name', sa.String(), nullable=False),
    sa.Column('account_type', sa.String(), nullable=True),
    sa.Column('is_liability', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('backfill_status', sa.String(), nullable=False),
    sa.Column('target_start_date', sa.Date(), nullable=True),
    sa.Column('target_end_date', sa.Date(), nullable=True),
    sa.Column('backfill_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('incremental_start_date', sa.Date(), nullable=True),
    sa.Column('incremental_end_date', sa.Date(), nullable=True),
    sa.Column('last_successful_window_start_date', sa.Date(), nullable=True),
    sa.Column('last_successful_window_end_date', sa.Date(), nullable=True),
    sa.Column('last_successful_fetch_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('incremental_start_date IS NULL OR incremental_end_date IS NULL OR incremental_start_date <= incremental_end_date', name='ck_transaction_import_states_incremental_date_order'),
    sa.CheckConstraint('last_successful_window_start_date IS NULL OR last_successful_window_end_date IS NULL OR last_successful_window_start_date <= last_successful_window_end_date', name='ck_transaction_import_states_success_date_order'),
    sa.CheckConstraint('target_start_date IS NULL OR target_end_date IS NULL OR target_start_date <= target_end_date', name='ck_transaction_import_states_target_date_order'),
    sa.ForeignKeyConstraint(['account_id', 'institution_id', 'user_id'], ['accounts.id', 'accounts.institution_id', 'accounts.user_id'], name='fk_transaction_import_states_account_connection_owner', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['institution_id', 'user_id'], ['institutions.id', 'institutions.user_id'], name='fk_transaction_import_states_connection_owner', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'institution_id', 'account_external_id', name='uq_transaction_import_account_states_connection_account')
    )
    with op.batch_alter_table('transaction_import_account_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_import_account_states_account_external_id'), ['account_external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_import_account_states_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_import_account_states_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_import_account_states_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_import_account_states_user_id'), ['user_id'], unique=False)

    op.create_table('transaction_import_windows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('account_external_id', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('window_start_date', sa.Date(), nullable=False),
    sa.Column('window_end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('sync_id', sa.String(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('attempt_count >= 0', name='ck_transaction_import_windows_attempt_count'),
    sa.CheckConstraint('transaction_count >= 0', name='ck_transaction_import_windows_transaction_count'),
    sa.CheckConstraint('window_start_date <= window_end_date', name='ck_transaction_import_windows_date_order'),
    sa.ForeignKeyConstraint(['account_id', 'institution_id', 'user_id'], ['accounts.id', 'accounts.institution_id', 'accounts.user_id'], name='fk_transaction_import_windows_account_connection_owner', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['institution_id', 'user_id'], ['institutions.id', 'institutions.user_id'], name='fk_transaction_import_windows_connection_owner', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'institution_id', 'account_external_id', 'mode', 'window_start_date', 'window_end_date', name='uq_transaction_import_windows_connection_account_window')
    )
    with op.batch_alter_table('transaction_import_windows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_import_windows_account_external_id'), ['account_external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_import_windows_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_import_windows_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_import_windows_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_import_windows_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_import_windows_sync_id'), ['sync_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_import_windows_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_import_windows_window_end_date'), ['window_end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_import_windows_window_start_date'), ['window_start_date'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('raw_amount', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=30, scale=12), nullable=True),
    sa.Column('price', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('commission', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('mcc', sa.String(), nullable=True),
    sa.Column('asset_category', sa.String(), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('provider_recurring', sa.Boolean(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('category_source', sa.String(), nullable=True),
    sa.Column('user_description', sa.String(), nullable=True),
    sa.Column('user_notes', sa.Text(), nullable=True),
    sa.Column('recurring_series_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id', 'user_id'], ['accounts.id', 'accounts.user_id'], name='fk_transactions_account_owner', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id', 'user_id'], ['categories.id', 'categories.user_id'], name='fk_transactions_category_owner'),
    sa.ForeignKeyConstraint(['recurring_series_id', 'user_id'], ['recurring_series.id', 'recurring_series.user_id'], name='fk_transactions_recurring_series_owner'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'external_id', name='uq_transactions_account_id_external_id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_recurring_series_id'), ['recurring_series_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_recurring_series_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_category_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_account_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('transaction_import_windows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_import_windows_window_start_date'))
        batch_op.drop_index(batch_op.f('ix_transaction_import_windows_window_end_date'))
        batch_op.drop_index(batch_op.f('ix_transaction_import_windows_user_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_import_windows_sync_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_import_windows_status'))
        batch_op.drop_index(batch_op.f('ix_transaction_import_windows_provider'))
        batch_op.drop_index(batch_op.f('ix_transaction_import_windows_institution_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_import_windows_account_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_import_windows_account_external_id'))

    op.drop_table('transaction_import_windows')
    with op.batch_alter_table('transaction_import_account_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_import_account_states_user_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_import_account_states_provider'))
        batch_op.drop_index(batch_op.f('ix_transaction_import_account_states_institution_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_import_account_states_account_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_import_account_states_account_external_id'))

    op.drop_table('transaction_import_account_states')
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_holdings_user_id'))
        batch_op.drop_index(batch_op.f('ix_holdings_account_id'))

    op.drop_table('holdings')
    with op.batch_alter_table('balance_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_balance_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_balance_history_date'))
        batch_op.drop_index(batch_op.f('ix_balance_history_account_id'))

    op.drop_table('balance_history')
    with op.batch_alter_table('transaction_import_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_import_jobs_user_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_import_jobs_sync_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_import_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_transaction_import_jobs_source_sync_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_import_jobs_provider'))
        batch_op.drop_index(batch_op.f('ix_transaction_import_jobs_lease_token'))
        batch_op.drop_index(batch_op.f('ix_transaction_import_jobs_last_progress_at'))
        batch_op.drop_index(batch_op.f('ix_transaction_import_jobs_job_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_import_jobs_institution_id'))

    op.drop_table('transaction_import_jobs')
    with op.batch_alter_table('recurring_series', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurring_series_user_id'))
        batch_op.drop_index(batch_op.f('ix_recurring_series_status'))
        batch_op.drop_index(batch_op.f('ix_recurring_series_merchant_key'))
        batch_op.drop_index(batch_op.f('ix_recurring_series_category_id'))

    op.drop_table('recurring_series')
    with op.batch_alter_table('connection_auth_artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connection_auth_artifacts_user_id'))
        batch_op.drop_index(batch_op.f('ix_connection_auth_artifacts_provider'))
        batch_op.drop_index(batch_op.f('ix_connection_auth_artifacts_institution_id'))

    op.drop_table('connection_auth_artifacts')
    with op.batch_alter_table('category_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_rules_user_id'))
        batch_op.drop_index(batch_op.f('ix_category_rules_priority'))
        batch_op.drop_index(batch_op.f('ix_category_rules_category_id'))

    op.drop_table('category_rules')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_user_id'))
        batch_op.drop_index(batch_op.f('ix_accounts_secured_asset_account_id'))
        batch_op.drop_index(batch_op.f('ix_accounts_institution_id'))

    op.drop_table('accounts')
    with op.batch_alter_table('visible_auth_attempt_artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visible_auth_attempt_artifacts_user_id'))
        batch_op.drop_index(batch_op.f('ix_visible_auth_attempt_artifacts_provider'))
        batch_op.drop_index(batch_op.f('ix_visible_auth_attempt_artifacts_attempt_id'))

    op.drop_table('visible_auth_attempt_artifacts')
    with op.batch_alter_table('user_secret_artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_secret_artifacts_user_id'))

    op.drop_table('user_secret_artifacts')
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settings_user_id'))

    op.drop_table('settings')
    with op.batch_alter_table('market_strip_snapshot_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_strip_snapshot_points_user_id'))
        batch_op.drop_index(batch_op.f('ix_market_strip_snapshot_points_symbol_key'))
        batch_op.drop_index(batch_op.f('ix_market_strip_snapshot_points_provider'))
        batch_op.drop_index(batch_op.f('ix_market_strip_snapshot_points_local_date'))

    op.drop_table('market_strip_snapshot_points')
    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.drop_index('uq_institutions_user_synced_provider')
        batch_op.drop_index(batch_op.f('ix_institutions_user_id'))

    op.drop_table('institutions')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_user_id'))
        batch_op.drop_index(batch_op.f('ix_categories_seed_key'))
        batch_op.drop_index(batch_op.f('ix_categories_parent_id'))

    op.drop_table('categories')
    op.drop_table('users')
    op.drop_table('symbol_sectors')
    op.drop_table('symbol_names')
    with op.batch_alter_table('fx_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fx_rates_date'))
        batch_op.drop_index(batch_op.f('ix_fx_rates_currency'))

    op.drop_table('fx_rates')
    with op.batch_alter_table('benchmark_prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_benchmark_prices_symbol'))
        batch_op.drop_index(batch_op.f('ix_benchmark_prices_provider'))
        batch_op.drop_index(batch_op.f('ix_benchmark_prices_date'))

    op.drop_table('benchmark_prices')
    # ### end Alembic commands ###
