const ISOLATED_ELECTRON_JOURNEY_FLAG = '--breaktwenty-isolated-electron-journey';
const ISOLATED_ELECTRON_RECEIPT_PREFIX = 'BREAKTWENTY_ISOLATED_ELECTRON_RECEIPT ';

module.exports = {
  ISOLATED_ELECTRON_JOURNEY_FLAG,
  ISOLATED_ELECTRON_RECEIPT_PREFIX,
};
