const BREAKTWENTY_OWNED_INSTITUTION_LOGO_KEYS = Object.freeze([
  'bank-brokerage',
  'cash',
  'crypto-wallet',
  'debt',
  'manual-institution',
  'other-assets',
  'private-investments',
  'real-estate',
  'valuables',
  'vehicles',
]);

function institutionLogoFilterTokens({ saturation = '1', contrast = '1', brightness = '1' } = {}) {
  return Object.freeze(Object.fromEntries(BREAKTWENTY_OWNED_INSTITUTION_LOGO_KEYS.flatMap((key) => [
    [`--institution-logo-${key}-saturation`, saturation],
    [`--institution-logo-${key}-contrast`, contrast],
    [`--institution-logo-${key}-brightness`, brightness],
  ])));
}

const neutralInstitutionLogoFilters = institutionLogoFilterTokens();
const lightInstitutionLogoFilters = Object.freeze({
  '--institution-logo-bank-brokerage-saturation': '1',
  '--institution-logo-bank-brokerage-contrast': '0.8',
  '--institution-logo-bank-brokerage-brightness': '1.1',
  '--institution-logo-cash-saturation': '1',
  '--institution-logo-cash-contrast': '0.8',
  '--institution-logo-cash-brightness': '0.8',
  '--institution-logo-crypto-wallet-saturation': '2',
  '--institution-logo-crypto-wallet-contrast': '0.8',
  '--institution-logo-crypto-wallet-brightness': '1',
  '--institution-logo-debt-saturation': '1.18',
  '--institution-logo-debt-contrast': '1',
  '--institution-logo-debt-brightness': '1',
  '--institution-logo-manual-institution-saturation': '1',
  '--institution-logo-manual-institution-contrast': '0.8',
  '--institution-logo-manual-institution-brightness': '0.8',
  '--institution-logo-other-assets-saturation': '1',
  '--institution-logo-other-assets-contrast': '1',
  '--institution-logo-other-assets-brightness': '0.9',
  '--institution-logo-private-investments-saturation': '1',
  '--institution-logo-private-investments-contrast': '1',
  '--institution-logo-private-investments-brightness': '0.9',
  '--institution-logo-real-estate-saturation': '1',
  '--institution-logo-real-estate-contrast': '0.8',
  '--institution-logo-real-estate-brightness': '0.9',
  '--institution-logo-valuables-saturation': '1',
  '--institution-logo-valuables-contrast': '0.8',
  '--institution-logo-valuables-brightness': '0.9',
  '--institution-logo-vehicles-saturation': '1',
  '--institution-logo-vehicles-contrast': '1.2',
  '--institution-logo-vehicles-brightness': '0.8',
});

export const breaktwentyRuntimeCssVariables = Object.freeze({
  dark: Object.freeze({
    '--app-canvas-bg': [
      'var(--app-canvas-material) center / cover no-repeat',
      'var(--color-bg)',
    ].join(',\n    '),
    '--sidebar-bg': [
      'var(--sidebar-material) center / var(--sidebar-material-size) repeat',
      'rgb(var(--rgb-surface))',
    ].join(',\n    '),
    '--sidebar-shadow': [
      '0 0 0 0.1rem rgba(0, 0, 0, 0.62)',
      '0.18rem 0 0.7rem -0.6rem rgba(var(--rgb-white), 0.05)',
    ].join(',\n    '),
    '--sidebar-icon-color': 'var(--color-text-secondary)',
    '--floating-nav-state-shell-hover-border-width': 'var(--surface-button-selected-border-width)',
    '--floating-nav-button-hover-shadow-theme': 'var(--surface-button-hover-shadow)',
    '--surface-button-app-material': 'var(--button-app-material) center / 100% 100% no-repeat',
    '--surface-button-on-panel-material': 'var(--button-panel-material) center / 100% 100% no-repeat',
    '--surface-button-selected-material': 'var(--button-selected-material) center / 100% 100% no-repeat',
    '--surface-expanded-parent-material': 'var(--expanded-parent-material) center / 100% 100% no-repeat',
    '--surface-expanded-parent-selected-material': 'var(--expanded-parent-selected-material) center / 100% 100% no-repeat',
    '--surface-accounts-child-material': 'var(--accounts-child-material) center / var(--accounts-child-material-size) repeat',
    '--button-overlay-shadow': 'var(--button-overlay-shadow-dark)',
    '--account-type-badge-bg-base': 'transparent',
    '--account-type-badge-bg-accent-mix': '0%',
    '--account-type-badge-bg-base-mix': '100%',
    '--account-type-badge-color-accent-mix': '100%',
    '--account-type-badge-color-text-mix': '0%',
    '--account-type-badge-border-accent-mix': '100%',
    '--account-type-badge-border-text-mix': '0%',
    '--institution-logo-stage-padding': '0px',
    '--institution-logo-stage-border-width': '0px',
    '--institution-logo-stage-border-color': 'transparent',
    '--institution-logo-stage-bg': 'transparent',
    '--institution-logo-stage-shadow': '0 0 0 0 transparent',
    ...neutralInstitutionLogoFilters,
    '--panel-shell-small-lighting-bg': 'var(--panel-shell-small-baked-lighting) center / 100% 100% no-repeat',
    '--panel-shell-lighting-bg': 'var(--panel-shell-baked-lighting) center / 100% 100% no-repeat',
    '--panel-shell-long-lighting-bg': 'var(--panel-shell-long-baked-lighting) center / 100% 100% no-repeat',
    '--panel-shell-table-lighting-bg': 'var(--panel-shell-table-baked-lighting) center / 100% 100% no-repeat',
    '--holdings-table-panel-bg': 'var(--surface-panel-long-bg)',
    '--holdings-table-row-divider': 'var(--surface-panel-long-row-divider)',
    '--holdings-table-footer-divider': 'var(--holdings-table-row-divider)',
    '--panel-inset-material-bg': [
      'var(--panel-material) center / var(--panel-inset-material-size) repeat',
      'rgb(var(--rgb-surface))',
    ].join(',\n    '),
    '--app-menu-shadow': '0 18px 38px rgba(0, 0, 0, 0.55)',
    '--tooltip-shadow': '0 0.75rem 1.75rem rgba(0, 0, 0, 0.32)',
    '--app-scrollbar-track': 'var(--app-scrollbar-track-dark)',
    '--app-scrollbar-track-bg': 'var(--app-scrollbar-track)',
    '--table-header-bg': [
      'var(--surface-button-on-panel-material)',
      'rgb(var(--rgb-surface-elevated))',
    ].join(',\n    '),
  }),
  light: Object.freeze({
    '--app-canvas-bg': [
      'var(--app-canvas-material-light) center / cover no-repeat',
      'var(--color-bg)',
    ].join(',\n    '),
    '--sidebar-bg': [
      'var(--sidebar-material-light) center / 100% var(--sidebar-material-repeat-height) repeat-y',
      'rgb(var(--rgb-surface))',
    ].join(',\n    '),
    '--sidebar-shadow': [
      '0 0 0 0.1rem rgba(var(--rgb-border), 0.35)',
      '0.1rem 0 0.1rem 0rem rgba(0, 0, 0, 0.2)',
    ].join(',\n    '),
    '--sidebar-icon-color': 'var(--color-accent-secondary)',
    '--floating-nav-state-shell-hover-border-width': 'var(--surface-button-selected-border-width)',
    '--floating-nav-button-hover-shadow-theme': 'var(--surface-button-hover-shadow)',
    '--surface-button-app-material': 'var(--button-app-material-light) center / 100% 100% no-repeat',
    '--surface-button-on-panel-material': 'var(--button-panel-material-light) center / 100% 100% no-repeat',
    '--surface-button-selected-material': 'var(--button-selected-material-light) center / 100% 100% no-repeat',
    '--surface-expanded-parent-material': 'var(--expanded-parent-material-light) center / 100% 100% no-repeat',
    '--surface-expanded-parent-selected-material': 'var(--expanded-parent-selected-material-light) center / 100% 100% no-repeat',
    '--surface-accounts-child-material': 'var(--accounts-child-material-light) center / var(--accounts-child-material-size) repeat',
    '--button-overlay-shadow': 'var(--button-overlay-shadow-light)',
    '--account-type-badge-bg-base': 'rgb(var(--rgb-surface))',
    '--account-type-badge-bg-accent-mix': '35%',
    '--account-type-badge-bg-base-mix': '80%',
    '--account-type-badge-color-accent-mix': '100%',
    '--account-type-badge-color-text-mix': '18%',
    '--account-type-badge-border-accent-mix': '100%',
    '--account-type-badge-border-text-mix': '100%',
    '--institution-logo-stage-padding': '0px',
    '--institution-logo-stage-border-width': '0px',
    '--institution-logo-stage-border-color': 'transparent',
    '--institution-logo-stage-bg': 'transparent',
    '--institution-logo-stage-shadow': '0 0 0 0 transparent',
    ...lightInstitutionLogoFilters,
    '--panel-shell-small-lighting-bg': [
      'var(--panel-shell-small-baked-lighting-light) center / 100% 100% no-repeat',
      'var(--surface-panel-material-bg)',
    ].join(',\n    '),
    '--panel-shell-lighting-bg': [
      'var(--panel-shell-baked-lighting-light) center / 100% 100% no-repeat',
      'var(--surface-panel-material-bg)',
    ].join(',\n    '),
    '--panel-shell-long-lighting-bg': [
      'var(--panel-shell-long-baked-lighting-light) center / 100% 100% no-repeat',
      'var(--surface-panel-material-bg)',
    ].join(',\n    '),
    '--panel-shell-table-lighting-bg': [
      'var(--panel-shell-table-baked-lighting-light) center / 100% 100% no-repeat',
      'var(--surface-panel-material-bg)',
    ].join(',\n    '),
    '--holdings-table-panel-bg': 'var(--surface-panel-long-bg)',
    '--holdings-table-row-divider': '1px solid color-mix(in srgb, rgb(var(--rgb-border)) 34%, rgb(var(--rgb-surface)) 66%)',
    '--holdings-table-footer-divider': 'var(--holdings-table-row-divider)',
    '--panel-inset-material-bg': [
      'var(--panel-material-light) center / var(--panel-inset-material-size) repeat',
      'rgb(var(--rgb-surface))',
    ].join(',\n    '),
    '--app-menu-shadow': '0 18px 38px rgba(0, 0, 0, 0.18)',
    '--tooltip-shadow': '0 0.75rem 1.75rem rgba(0, 0, 0, 0.16)',
    '--app-scrollbar-track': 'var(--app-scrollbar-track-light)',
    '--app-scrollbar-track-bg': 'var(--app-scrollbar-track)',
    '--dashboard-customize-switch-on-thumb': 'var(--color-active-text)',
    '--table-header-bg': [
      'var(--surface-button-selected-material)',
      'rgb(var(--rgb-surface-elevated))',
    ].join(',\n    '),
    '--date-band-bg': 'rgb(251, 248, 242)',
    '--date-band-shadow': [
      'inset 0 1px 0 rgba(var(--rgb-white), 0.38)',
      'inset 0 -1px 0 rgba(0, 0, 0, 0.14)',
    ].join(',\n    '),
    '--date-band-color': 'var(--color-data-highlight-text)',
    '--textual-tab-active-color': 'var(--color-text-secondary)',
    '--close-button-hover-color': 'var(--color-data-highlight-text)',
    '--close-button-hover-border-color': 'var(--color-data-highlight-text)',
  }),
});
