// SINGLE SOURCE OF TRUTH for semantic surface-layer tokens; the private development workspace owns the theme specification.
// scripts/generate-theme-css.js compiles breaktwentySurfaceCssVariables with the color
// and typography maps into src/theme/tokens.generated.css for first paint;
// applyBreakTwentySurfaces() installs the same map at runtime. Keep this file
// dependency-free (no imports) — the generator evaluates it standalone.

export const breaktwentySurfaceThemes = Object.freeze({
  dark: Object.freeze({
    '--surface-floating-bg': 'var(--surface-modal-bg)',
    '--surface-floating-border-width': 'var(--open-button-border-width)',
    '--surface-floating-border-color': 'var(--open-button-border-color)',
    '--surface-floating-header-bg': 'var(--surface-floating-bg)',
    '--surface-floating-radius': 'var(--surface-panel-radius)',
    '--surface-floating-shadow': 'var(--app-menu-shadow)',
    '--surface-modal-bg': [
      'var(--modal-material) center / 100% 100% no-repeat',
      'rgb(var(--rgb-surface-elevated))',
    ].join(',\n    '),
    '--surface-modal-border-width': 'var(--surface-floating-border-width)',
    '--surface-modal-border-color': 'var(--surface-floating-border-color)',
    '--surface-modal-radius': 'var(--surface-floating-radius)',
    '--surface-modal-shadow': 'var(--surface-floating-shadow)',
    '--surface-text-field-bg': [
      'linear-gradient(180deg, rgba(var(--rgb-surface-elevated), 0.2), rgba(var(--rgb-surface-elevated), 0.2))',
      'linear-gradient(180deg, rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5))',
      'var(--surface-input-bg)',
    ].join(',\n    '),
    '--surface-text-field-border-width': '1px',
    '--surface-text-field-border-color': 'rgb(93, 88, 81)',
    '--surface-text-field-focus-border-color': 'var(--surface-text-field-border-color)',
    '--surface-text-field-radius': 'var(--radius-sm)',
    '--surface-text-field-shadow': 'none',
    '--surface-text-field-color': 'var(--type-input-color)',
    '--surface-text-field-placeholder-color': 'var(--color-text-faint)',
    '--surface-tray-bg': 'var(--surface-panel-bg)',
    '--surface-tray-border-width': 'var(--surface-panel-border-width)',
    '--surface-tray-border-color': 'var(--open-button-border-color)',
    '--surface-tray-radius': 'var(--surface-panel-radius)',
    '--surface-tray-shadow': 'var(--surface-panel-shadow)',
    '--surface-tray-box-bg': 'var(--surface-inset-layer-bg)',
    '--surface-tray-box-border-width': 'var(--surface-inset-layer-border-width)',
    '--surface-tray-box-border-color': 'var(--surface-inset-layer-border-color)',
    '--surface-tray-box-radius': 'var(--surface-inset-layer-radius)',
    '--surface-tray-box-shadow': 'var(--surface-inset-layer-shadow)',
    '--surface-inset-layer-bg': [
      'var(--inset-layer-material) center / 100% 100% no-repeat',
      'rgb(var(--rgb-surface))',
    ].join(',\n    '),
    '--surface-inset-layer-border-width': 'var(--surface-floating-border-width)',
    '--surface-inset-layer-border-color': 'rgb(93, 88, 81)',
    '--surface-inset-layer-radius': 'var(--surface-floating-radius)',
    '--surface-inset-layer-shadow': 'none',
    '--surface-tray-child-bg': 'var(--surface-panel-small-bg)',
    '--surface-tray-child-border-width': 'var(--surface-panel-border-width)',
    '--surface-tray-child-border-color': 'var(--surface-panel-border-color)',
    '--surface-tray-child-radius': 'var(--surface-panel-radius)',
    '--surface-tray-child-shadow': 'var(--surface-panel-shadow)',
    '--surface-accounts-parent-row-bg': 'var(--surface-expanded-parent-bg)',
    '--surface-accounts-parent-row-border-width': 'var(--surface-expanded-parent-border-width)',
    '--surface-accounts-parent-row-border-color': 'var(--surface-expanded-parent-border-color)',
    '--surface-accounts-parent-row-shadow': 'var(--surface-expanded-parent-shadow)',
    '--surface-expanded-parent-bg': [
      'var(--surface-expanded-parent-material)',
      'rgb(var(--rgb-surface))',
    ].join(',\n    '),
    '--surface-expanded-parent-border-width': 'var(--surface-button-on-panel-border-width)',
    '--surface-expanded-parent-border-color': 'var(--surface-panel-border-color)',
    '--surface-expanded-parent-shadow': 'var(--surface-button-on-panel-shadow)',
    '--surface-expanded-parent-state-border-width': 'var(--floating-nav-state-shell-selected-border-width)',
    '--surface-expanded-parent-state-border-color': 'rgba(var(--rgb-active-border), 0.5)',
    '--surface-expanded-parent-state-frame-border-width': '0',
    '--surface-expanded-parent-state-frame-border-color': 'transparent',
    '--surface-expanded-parent-state-frame-shadow': '0 0 0 var(--surface-expanded-parent-state-border-width) var(--surface-expanded-parent-state-border-color)',
    '--surface-expanded-parent-selected-bg': [
      'var(--surface-expanded-parent-selected-material)',
      'rgb(var(--rgb-surface))',
    ].join(',\n    '),
    '--surface-expanded-parent-hover-bg': 'var(--surface-expanded-parent-selected-bg)',
    '--surface-expanded-child-bg': [
      'var(--surface-accounts-child-material)',
      'rgb(var(--rgb-surface))',
    ].join(',\n    '),
    '--surface-expanded-child-shadow': 'none',
    '--surface-expanded-child-row-bg': 'transparent',
    '--surface-expanded-child-row-divider': 'var(--surface-panel-long-row-divider)',
    '--surface-tray-ticker-bg': 'var(--surface-modal-bg)',
    '--surface-tray-ticker-border-width': '1px',
    '--surface-tray-ticker-border-color': 'rgba(var(--rgb-shell-accent), 0.35)',
    '--surface-tray-ticker-radius': 'var(--surface-modal-radius)',
    '--surface-tray-ticker-shadow': 'none',
    '--surface-row-bg': 'var(--surface-button-on-panel-bg)',
    '--surface-row-hover-bg': 'var(--surface-button-hover-bg)',
    '--surface-row-border-width': 'var(--surface-button-on-panel-border-width)',
    '--surface-row-border-color': 'var(--surface-button-on-panel-border-color)',
    '--surface-row-hover-color': 'var(--surface-button-hover-color)',
    '--surface-row-hover-border-color': 'var(--color-data-highlight-border)',
    '--surface-row-hover-shadow': 'var(--surface-button-hover-shadow)',
    '--surface-row-warning-bg': [
      'linear-gradient(180deg, rgba(var(--rgb-warning), 0.14), rgba(var(--rgb-surface), 0.82))',
      'rgb(var(--rgb-surface))',
    ].join(',\n    '),
    '--surface-inset-bg': 'var(--highlighted-surface-bg)',
    '--surface-inset-hover-bg': 'var(--surface-inset-bg)',
    '--surface-inset-border-width': 'var(--surface-button-on-panel-border-width)',
    '--surface-inset-border-color': 'var(--surface-row-border-color)',
    '--surface-inset-hover-border-width': 'var(--surface-row-hover-border-width)',
    '--surface-inset-hover-border-color': 'var(--surface-row-hover-border-color)',
    '--surface-inset-shadow': 'none',
    '--surface-nested-bg': 'var(--panel-inset-material-bg)',
    '--surface-nested-deep-bg': [
      'var(--panel-material) center / var(--panel-material-size) repeat',
      'rgb(var(--rgb-surface))',
    ].join(',\n    '),
    '--surface-nested-border-width': 'var(--surface-button-on-panel-border-width)',
    '--surface-nested-border-color': 'rgba(var(--rgb-shell-accent), 0.28)',
    '--surface-nested-shadow': [
      'inset 0 1px 0 rgba(var(--rgb-white), 0.08)',
      '0 6px 14px rgba(0, 0, 0, 0.12)',
    ].join(',\n    '),
    '--surface-button-app-bg': [
      'var(--surface-button-app-material)',
      'rgb(var(--rgb-surface))',
    ].join(',\n    '),
    '--surface-button-app-color': 'var(--color-text-primary)',
    '--surface-button-app-border-width': '1px',
    '--surface-button-app-border-color': 'rgb(93, 88, 81)',
    '--surface-button-app-inset-shadow': 'inset 0 0 0 0 rgba(0, 0, 0, 0)',
    '--surface-button-app-outer-shadow': '0px 1px 2px rgba(0, 0, 0, 1.5)',
    '--surface-button-app-shadow': [
      'var(--surface-button-app-inset-shadow)',
      'var(--surface-button-app-outer-shadow)',
    ].join(',\n    '),
    '--surface-button-on-panel-bg': [
      'var(--surface-button-on-panel-material)',
      'rgb(var(--rgb-surface))',
    ].join(',\n    '),
    '--surface-button-on-panel-color': 'var(--color-text-primary)',
    '--surface-button-on-panel-border-width': '1px',
    '--surface-button-on-panel-border-color': 'rgb(93, 88, 81)',
    '--surface-button-on-panel-inset-shadow': 'inset 0 0 0 0 rgba(0, 0, 0, 0)',
    '--surface-button-on-panel-outer-shadow': '0 1px 2px rgba(0, 0, 0, 1.5)',
    '--surface-button-on-panel-shadow': [
      'var(--surface-button-on-panel-inset-shadow)',
      'var(--surface-button-on-panel-outer-shadow)',
    ].join(',\n    '),
    '--surface-button-hover-bg': 'var(--surface-button-selected-bg)',
    '--surface-button-hover-color': 'var(--surface-button-selected-color)',
    '--surface-button-hover-border-color': 'var(--surface-button-selected-border-color)',
    '--surface-button-hover-inset-shadow': 'var(--surface-button-selected-inset-shadow)',
    '--surface-button-hover-outer-shadow': 'var(--surface-button-selected-outer-shadow)',
    '--surface-button-hover-shadow': [
      'var(--surface-button-hover-inset-shadow)',
      'var(--surface-button-hover-outer-shadow)',
    ].join(',\n    '),
    '--surface-button-selected-bg': [
      'var(--surface-button-selected-material)',
      'rgb(var(--rgb-surface))',
    ].join(',\n    '),
    '--surface-button-selected-color': 'var(--color-active-text)',
    '--surface-button-selected-border-color': 'rgba(var(--rgb-active-border), 1)',
    '--surface-button-selected-inset-shadow': 'inset 0 0 0 var(--button-state-inset-rim-width-effective) rgba(var(--rgb-active-inset), 0.5)',
    '--surface-button-selected-outer-shadow': '0 0 0 0 rgba(0, 0, 0, 0)',
    '--surface-button-selected-shadow': [
      'var(--surface-button-selected-inset-shadow)',
      'var(--surface-button-selected-outer-shadow)',
    ].join(',\n    '),
    '--surface-input-bg': 'rgb(var(--rgb-bg))',
    '--surface-subpanel-bg': 'rgb(var(--rgb-surface))',
    '--surface-panel-material-bg': [
      'var(--panel-material) center / var(--panel-material-size) repeat',
      'rgb(var(--rgb-surface))',
    ].join(',\n    '),
    '--surface-panel-lighting-bg': 'none',
    '--surface-panel-bg': 'var(--panel-shell-lighting-bg)',
    '--surface-panel-small-bg': 'var(--panel-shell-small-lighting-bg)',
    '--surface-panel-long-bg': 'var(--panel-shell-long-lighting-bg)',
    '--surface-panel-table-bg': 'var(--panel-shell-table-lighting-bg)',
    '--surface-panel-border-width': '1px',
    '--surface-panel-border-color': 'rgb(71, 68, 61)',
    '--surface-panel-radius': '0.7rem',
    '--surface-panel-rim-shadow': [
      'inset 0 0 0 1px rgba(0, 0, 0, 0.26)',
      'inset 0 0 0.2rem rgba(0, 0, 0, 0.05)',
      'inset 0 0 0.6rem rgba(0, 0, 0, 0.5)',
      'inset 0 0 0.2rem rgba(0, 0, 0, 0.05)',
    ].join(',\n    '),
    '--surface-panel-shadow': [
      'var(--surface-panel-rim-shadow)',
      '0 0.15rem 0rem 0rem rgba(0, 0, 0, 0.3)',
      '0 0.3rem 1rem 0.25rem rgba(0, 0, 0, 0.025)',
    ].join(',\n    '),
    '--surface-panel-long-shadow': 'var(--surface-panel-shadow)',
    '--surface-panel-table-shadow': 'var(--surface-panel-shadow)',
    '--surface-panel-row-divider': '1px solid rgba(var(--rgb-white), 0.018)',
    '--surface-panel-long-row-divider': 'var(--surface-panel-row-divider)',
    '--surface-panel-divider-color': 'rgba(var(--rgb-border), 0.55)',
  }),
  light: Object.freeze({
    '--surface-floating-bg': 'var(--surface-modal-bg)',
    '--surface-floating-border-width': '3px',
    '--surface-floating-border-color': 'var(--color-data-highlight-border)',
    '--surface-floating-header-bg': 'var(--surface-floating-bg)',
    '--surface-floating-radius': 'var(--surface-panel-radius)',
    '--surface-floating-shadow': 'var(--app-menu-shadow)',
    '--surface-modal-bg': [
      'var(--modal-material-light) center / 100% 100% no-repeat',
      'rgb(var(--rgb-surface-elevated))',
    ].join(',\n    '),
    '--surface-modal-border-width': 'var(--surface-floating-border-width)',
    '--surface-modal-border-color': 'var(--surface-floating-border-color)',
    '--surface-modal-radius': 'var(--surface-floating-radius)',
    '--surface-modal-shadow': [
      'var(--surface-panel-rim-shadow)',
      'var(--surface-floating-shadow)',
    ].join(',\n    '),
    '--surface-text-field-bg': 'rgb(var(--rgb-bg))',
    '--surface-text-field-border-width': '1px',
    '--surface-text-field-border-color': 'rgba(var(--rgb-border), 0.62)',
    '--surface-text-field-focus-border-color': 'var(--surface-text-field-border-color)',
    '--surface-text-field-radius': 'var(--radius-sm)',
    '--surface-text-field-shadow': 'inset 0 1px 0 rgba(var(--rgb-white), 0.64)',
    '--surface-text-field-color': 'var(--type-input-color)',
    '--surface-text-field-placeholder-color': 'var(--color-text-faint)',
    '--surface-tray-bg': 'var(--surface-panel-bg)',
    '--surface-tray-border-width': 'var(--surface-panel-border-width)',
    '--surface-tray-border-color': 'var(--color-data-highlight-border)',
    '--surface-tray-radius': 'var(--surface-panel-radius)',
    '--surface-tray-shadow': 'var(--surface-panel-shadow)',
    '--surface-tray-box-bg': 'var(--surface-inset-layer-bg)',
    '--surface-tray-box-border-width': 'var(--surface-inset-layer-border-width)',
    '--surface-tray-box-border-color': 'var(--surface-inset-layer-border-color)',
    '--surface-tray-box-radius': 'var(--surface-inset-layer-radius)',
    '--surface-tray-box-shadow': 'var(--surface-inset-layer-shadow)',
    '--surface-inset-layer-bg': [
      'var(--inset-layer-material-light) center / 100% 100% no-repeat',
      'rgb(var(--rgb-surface))',
    ].join(',\n    '),
    '--surface-inset-layer-border-width': 'var(--surface-floating-border-width)',
    '--surface-inset-layer-border-color': 'rgb(var(--rgb-border))',
    '--surface-inset-layer-radius': 'var(--surface-floating-radius)',
    '--surface-inset-layer-shadow': 'none',
    '--surface-tray-child-bg': 'var(--surface-panel-small-bg)',
    '--surface-tray-child-border-width': 'var(--surface-panel-border-width)',
    '--surface-tray-child-border-color': 'var(--surface-panel-border-color)',
    '--surface-tray-child-radius': 'var(--surface-panel-radius)',
    '--surface-tray-child-shadow': 'var(--surface-panel-shadow)',
    '--surface-accounts-parent-row-bg': 'var(--surface-expanded-parent-bg)',
    '--surface-accounts-parent-row-border-width': 'var(--surface-expanded-parent-border-width)',
    '--surface-accounts-parent-row-border-color': 'var(--surface-expanded-parent-border-color)',
    '--surface-accounts-parent-row-shadow': 'var(--surface-expanded-parent-shadow)',
    '--surface-expanded-parent-bg': [
      'var(--surface-expanded-parent-material)',
      'rgb(var(--rgb-surface))',
    ].join(',\n    '),
    '--surface-expanded-parent-border-width': 'var(--surface-button-on-panel-border-width)',
    '--surface-expanded-parent-border-color': 'var(--surface-button-on-panel-border-color)',
    '--surface-expanded-parent-shadow': 'var(--surface-button-on-panel-shadow)',
    '--surface-expanded-parent-state-border-width': 'var(--floating-nav-state-shell-selected-border-width)',
    '--surface-expanded-parent-state-border-color': 'rgba(var(--rgb-active-border), 1)',
    '--surface-expanded-parent-state-frame-border-width': 'var(--button-state-shell-selected-border-width)',
    '--surface-expanded-parent-state-frame-border-color': 'var(--surface-button-selected-border-color)',
    '--surface-expanded-parent-state-frame-shadow': 'none',
    '--surface-expanded-parent-selected-bg': [
      'var(--surface-expanded-parent-selected-material)',
      'rgb(var(--rgb-surface))',
    ].join(',\n    '),
    '--surface-expanded-parent-hover-bg': 'var(--surface-expanded-parent-selected-bg)',
    '--surface-expanded-child-bg': [
      'var(--surface-accounts-child-material)',
      'rgb(var(--rgb-surface))',
    ].join(',\n    '),
    '--surface-expanded-child-shadow': 'none',
    '--surface-expanded-child-row-bg': 'transparent',
    '--surface-expanded-child-row-divider': 'var(--surface-panel-long-row-divider)',
    '--surface-tray-ticker-bg': 'var(--surface-modal-bg)',
    '--surface-tray-ticker-border-width': '1px',
    '--surface-tray-ticker-border-color': 'rgba(var(--rgb-shell-accent), 0.36)',
    '--surface-tray-ticker-radius': 'var(--surface-modal-radius)',
    '--surface-tray-ticker-shadow': 'none',
    '--surface-row-bg': 'var(--surface-button-on-panel-bg)',
    '--surface-row-hover-bg': 'var(--surface-button-hover-bg)',
    '--surface-row-border-width': 'var(--surface-button-on-panel-border-width)',
    '--surface-row-border-color': 'var(--surface-button-on-panel-border-color)',
    '--surface-row-hover-color': 'var(--surface-button-hover-color)',
    '--surface-row-hover-border-color': 'var(--color-data-highlight-border)',
    '--surface-row-hover-shadow': 'var(--surface-button-hover-shadow)',
    '--surface-row-warning-bg': [
      'linear-gradient(180deg, rgba(var(--rgb-warning), 0.12), rgba(var(--rgb-surface), 0.84))',
      'rgb(var(--rgb-surface))',
    ].join(',\n    '),
    '--surface-inset-bg': 'var(--highlighted-surface-bg)',
    '--surface-inset-hover-bg': 'var(--surface-inset-bg)',
    '--surface-inset-border-width': 'var(--surface-button-on-panel-border-width)',
    '--surface-inset-border-color': 'var(--surface-row-border-color)',
    '--surface-inset-hover-border-width': 'var(--surface-row-hover-border-width)',
    '--surface-inset-hover-border-color': 'var(--surface-row-hover-border-color)',
    '--surface-inset-shadow': 'none',
    '--surface-nested-bg': 'var(--panel-inset-material-bg)',
    '--surface-nested-deep-bg': [
      'var(--panel-material-light) center / var(--panel-material-size) repeat',
      'rgb(var(--rgb-surface))',
    ].join(',\n    '),
    '--surface-nested-border-width': 'var(--surface-button-on-panel-border-width)',
    '--surface-nested-border-color': 'rgba(var(--rgb-shell-accent), 0.24)',
    '--surface-nested-shadow': [
      'inset 0 1px 0 rgba(var(--rgb-white), 0.64)',
      '0 0.35rem 0.9rem rgba(0, 0, 0, 0.08)',
    ].join(',\n    '),
    '--surface-button-app-bg': [
      'var(--surface-button-app-material)',
      'rgb(var(--rgb-surface))',
    ].join(',\n    '),
    '--surface-button-app-color': 'var(--color-text-primary)',
    '--surface-button-app-border-width': '1.5px',
    '--surface-button-app-border-color': 'rgba(var(--rgb-border), 0.9)',
    '--surface-button-app-inset-shadow': 'inset 0 0 0 0 rgba(0, 0, 0, 0)',
    '--surface-button-app-outer-shadow': '0 1px 0 rgba(0, 0, 0, 0.38), 0.25px 1px 1.25px rgba(0, 0, 0, 0.72)',
    '--surface-button-app-shadow': [
      'var(--surface-button-app-inset-shadow)',
      'var(--surface-button-app-outer-shadow)',
    ].join(',\n    '),
    '--surface-button-on-panel-bg': [
      'var(--surface-button-on-panel-material)',
      'rgb(var(--rgb-surface))',
    ].join(',\n    '),
    '--surface-button-on-panel-color': 'var(--color-text-primary)',
    '--surface-button-on-panel-border-width': '1.5px',
    '--surface-button-on-panel-border-color': 'rgba(var(--rgb-border), 0.9)',
    '--surface-button-on-panel-inset-shadow': 'inset 0 0 0 0 rgba(0, 0, 0, 0)',
    '--surface-button-on-panel-outer-shadow': '0 1px 0 rgba(0, 0, 0, 0.38), 0.25px 1px 1.25px rgba(0, 0, 0, 0.72)',
    '--surface-button-on-panel-shadow': [
      'var(--surface-button-on-panel-inset-shadow)',
      'var(--surface-button-on-panel-outer-shadow)',
    ].join(',\n    '),
    '--surface-button-hover-bg': 'var(--surface-button-selected-bg)',
    '--surface-button-hover-color': 'var(--surface-button-selected-color)',
    '--surface-button-hover-border-color': 'rgba(var(--rgb-active-border), 1)',
    '--surface-button-hover-inset-shadow': 'var(--surface-button-selected-inset-shadow)',
    '--surface-button-hover-outer-shadow': 'var(--surface-button-selected-outer-shadow)',
    '--surface-button-hover-shadow': [
      'var(--surface-button-hover-inset-shadow)',
      'var(--surface-button-hover-outer-shadow)',
    ].join(',\n    '),
    '--surface-button-selected-bg': [
      'var(--surface-button-selected-material)',
      'rgb(var(--rgb-surface))',
    ].join(',\n    '),
    '--surface-button-selected-color': 'var(--color-active-text)',
    '--surface-button-selected-border-color': 'rgba(var(--rgb-active-border), 1)',
    '--surface-button-selected-inset-shadow': 'inset 0 0 0 var(--button-state-inset-rim-width-effective) rgba(var(--rgb-active-inset), 0.5)',
    '--surface-button-selected-outer-shadow': '0 0 0 0 rgba(0, 0, 0, 0)',
    '--surface-button-selected-shadow': [
      'var(--surface-button-selected-inset-shadow)',
      'var(--surface-button-selected-outer-shadow)',
    ].join(',\n    '),
    '--surface-input-bg': 'rgb(var(--rgb-bg))',
    '--surface-subpanel-bg': 'rgb(var(--rgb-surface))',
    '--surface-panel-material-bg': [
      'var(--panel-material-light) center / var(--panel-material-size) repeat',
      'rgb(var(--rgb-surface))',
    ].join(',\n    '),
    '--surface-panel-lighting-bg': 'none',
    '--surface-panel-bg': 'var(--panel-shell-lighting-bg)',
    '--surface-panel-small-bg': 'var(--panel-shell-small-lighting-bg)',
    '--surface-panel-long-bg': 'var(--panel-shell-long-lighting-bg)',
    '--surface-panel-table-bg': 'var(--panel-shell-table-lighting-bg)',
    '--surface-panel-border-width': '1px',
    '--surface-panel-border-color': 'rgb(var(--rgb-border))',
    '--surface-panel-radius': '0.7rem',
    '--surface-panel-rim-shadow': [
      'inset 0 1px 0 rgba(var(--rgb-white), 0.42)',
      'inset 0 -0.1rem 0.5rem rgba(0, 0, 0, 0.3)',
      'inset 0 0 0.2rem rgba(0, 0, 0, 0.1)',
    ].join(',\n    '),
    '--surface-panel-shadow': [
      'var(--surface-panel-rim-shadow)',
      '0.05rem 0.05rem 0rem rgba(0, 0, 0, 0.5)',
    ].join(',\n    '),
    '--surface-panel-long-shadow': 'var(--surface-panel-shadow)',
    '--surface-panel-table-shadow': 'var(--surface-panel-shadow)',
    '--surface-panel-row-divider': '1px solid rgba(var(--rgb-border), 0.34)',
    '--surface-panel-long-row-divider': 'var(--surface-panel-row-divider)',
    '--surface-panel-divider-color': 'rgba(var(--rgb-border), 0.5)',
  }),
});

export const breaktwentySurfaceCssVariables = breaktwentySurfaceThemes.dark;

function defaultSurfaceTarget() {
  return typeof document !== 'undefined' ? document.documentElement : null;
}

export function normalizeBreakTwentySurfaceThemeMode(mode) {
  return Object.prototype.hasOwnProperty.call(breaktwentySurfaceThemes, mode) ? mode : 'dark';
}

export function getBreakTwentySurfaceTheme(mode = 'dark') {
  return breaktwentySurfaceThemes[normalizeBreakTwentySurfaceThemeMode(mode)];
}

export function applyBreakTwentySurfaces(mode = 'dark', target = defaultSurfaceTarget()) {
  if (!target?.style) return;

  const normalizedMode = normalizeBreakTwentySurfaceThemeMode(mode);

  Object.entries(getBreakTwentySurfaceTheme(normalizedMode)).forEach(([name, value]) => {
    target.style.setProperty(name, value);
  });

  return normalizedMode;
}
