// SINGLE SOURCE OF TRUTH for all typography tokens; the private development workspace owns the theme specification.
// scripts/generate-theme-css.js compiles breaktwentyTypographyCssVariables (+ the color and surface
// maps) into src/theme/tokens.generated.css for first paint; applyBreakTwentyTypography()
// installs the same map at runtime. Keep this file dependency-free (no imports) —
// the generator evaluates it standalone.

const breaktwentyFontFamilies = Object.freeze({
  sans: "'Inter', system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
  uiLabel: "var(--font-family-sans)",
  mono: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
});

const breaktwentyFontWeights = Object.freeze({
  regular: 400,
  medium: 500,
  semibold: 600,
  bold: 700,
  strong: 700,
  // heavy used to be 700 (same as bold/strong). Knocked down one step to 600 to
  // soften the big stat numbers app-wide (dashboard/investments metric values,
  // Holdings summaries, etc.) for a calmer Monarch-like read. To revert: 700.
  heavy: 600,
});

export const breaktwentyTypographyCssVariables = Object.freeze({
  '--font-family-sans': breaktwentyFontFamilies.sans,
  '--font-family-ui-label': breaktwentyFontFamilies.uiLabel,
  '--font-family-mono': breaktwentyFontFamilies.mono,
  '--font-size-11': '0.6875rem',
  '--font-size-12': '0.75rem',
  '--font-size-13': '0.8125rem',
  '--font-size-14': '0.875rem',
  '--font-size-16': '1rem',
  '--font-size-18': '1.125rem',
  '--font-size-23': '1.4375rem',
  '--font-size-28': '1.75rem',
  '--font-size-36': '2.25rem',
  '--font-weight-regular': String(breaktwentyFontWeights.regular),
  '--font-weight-medium': String(breaktwentyFontWeights.medium),
  '--font-weight-semibold': String(breaktwentyFontWeights.semibold),
  '--font-weight-bold': String(breaktwentyFontWeights.bold),
  '--font-weight-strong': String(breaktwentyFontWeights.strong),
  '--font-weight-heavy': String(breaktwentyFontWeights.heavy),
  '--line-height-snug': '1.2',
  '--line-height-normal': '1.5',
  '--line-height-none': '1',
  '--line-height-tight': '1.25',
  '--tracking-tight': '-0.01em',
  '--tracking-snug': '0.02em',
  '--tracking-wide': '0.04em',
  '--tracking-caps': '0.06em',
  '--tracking-wider': '0.1em',
  '--type-page-title-family': 'var(--font-family-sans)',
  '--type-page-title-size': 'var(--font-size-23)',
  '--type-page-title-weight': 'var(--font-weight-strong)',
  '--type-page-title-color': 'var(--color-text-primary)',
  '--type-page-title-line-height': 'var(--line-height-snug)',
  '--type-page-title-letter-spacing': '0',
  '--type-topbar-title-family': 'var(--font-family-sans)',
  '--type-topbar-title-size': 'var(--font-size-23)',
  '--type-topbar-title-weight': 'var(--font-weight-strong)',
  '--type-topbar-title-color': 'var(--color-text-primary)',
  '--type-topbar-title-line-height': 'var(--line-height-snug)',
  '--type-topbar-title-letter-spacing': '0',
  '--type-panel-title-family': 'var(--font-family-sans)',
  '--type-panel-title-size': 'var(--font-size-16)',
  '--type-panel-title-weight': 'var(--font-weight-bold)',
  '--type-panel-title-color': 'var(--color-text-primary)',
  '--type-panel-title-line-height': 'var(--line-height-tight)',
  '--type-panel-title-letter-spacing': 'var(--tracking-wide)',
  '--type-subsection-title-family': 'var(--font-family-sans)',
  '--type-subsection-title-size': 'var(--font-size-12)',
  '--type-subsection-title-weight': 'var(--font-weight-bold)',
  '--type-subsection-title-color': 'var(--color-text-secondary)',
  '--type-subsection-title-line-height': 'var(--line-height-tight)',
  '--type-subsection-title-letter-spacing': 'var(--tracking-caps)',
  '--type-modal-title-family': 'var(--font-family-sans)',
  '--type-modal-title-size': 'var(--font-size-18)',
  '--type-modal-title-weight': 'var(--font-weight-semibold)',
  '--type-modal-title-color': 'var(--color-text-primary)',
  '--type-modal-title-line-height': 'var(--line-height-tight)',
  '--type-modal-title-letter-spacing': '0',
  '--type-loading-catchphrase-family': 'var(--font-family-sans)',
  '--type-loading-catchphrase-size': 'var(--loading-screen-catchphrase-size)',
  '--type-loading-catchphrase-weight': 'var(--font-weight-semibold)',
  '--type-loading-catchphrase-color': 'var(--color-text-secondary)',
  '--type-loading-catchphrase-line-height': 'var(--line-height-normal)',
  '--type-loading-catchphrase-letter-spacing': '0',
  '--type-institution-name-family': 'var(--font-family-sans)',
  '--type-institution-name-size': 'var(--font-size-14)',
  '--type-institution-name-weight': 'var(--font-weight-semibold)',
  '--type-institution-name-color': 'var(--color-text-primary)',
  '--type-institution-name-line-height': 'var(--line-height-snug)',
  '--type-institution-name-letter-spacing': '0',
  '--type-account-name-family': 'var(--font-family-sans)',
  '--type-account-name-size': 'var(--font-size-14)',
  '--type-account-name-weight': 'var(--font-weight-medium)',
  '--type-account-name-color': 'var(--color-text-primary)',
  '--type-account-name-line-height': 'var(--line-height-snug)',
  '--type-account-name-letter-spacing': '0',
  '--type-account-name-compact-size': 'var(--font-size-12)',
  '--type-account-name-compact-weight': 'var(--font-weight-semibold)',
  '--type-meta-family': 'var(--font-family-sans)',
  '--type-meta-size': 'var(--font-size-11)',
  '--type-meta-weight': 'var(--font-weight-regular)',
  '--type-meta-color': 'var(--color-text-secondary)',
  '--type-meta-line-height': '1.35',
  '--type-meta-letter-spacing': '0',
  '--type-body-size': 'var(--font-size-13)',
  '--type-body-large-size': 'var(--font-size-14)',
  '--type-body-xl-size': 'var(--font-size-16)',
  '--type-secondary-size': 'var(--font-size-12)',
  '--type-body-muted-family': 'var(--font-family-sans)',
  // body-muted (modal/card explanatory prose) is CHAINED to field-hint — one
  // master dial for all guidance prose; re-point these to detach modal copy.
  '--type-body-muted-size': 'var(--type-field-hint-size)',
  '--type-body-muted-weight': 'var(--type-field-hint-weight)',
  '--type-body-muted-color': 'var(--type-field-hint-color)',
  '--type-body-muted-letter-spacing': '0',
  // Panel/section count subtitle ("18 Positions", "Last N transactions") — its
  // own size knob; defaults to the body/hint 13px tier + regular like meta.
  '--type-section-count-size': 'var(--font-size-13)',
  '--type-section-count-color': 'var(--color-text-faint)',
  '--type-table-header-family': 'var(--font-family-sans)',
  '--type-table-header-size': 'var(--font-size-11)',
  '--type-table-header-weight': 'var(--font-weight-semibold)',
  '--type-table-header-color': 'var(--color-text-secondary)',
  '--type-table-header-line-height': 'var(--line-height-tight)',
  '--type-table-header-letter-spacing': '0',
  '--type-large-table-header-family': 'var(--type-table-header-family)',
  '--type-large-table-header-size': 'var(--font-size-13)',
  '--type-large-table-header-weight': 'var(--type-table-header-weight)',
  '--type-large-table-header-color': 'var(--type-table-header-color)',
  '--type-large-table-header-line-height': 'var(--type-table-header-line-height)',
  '--type-large-table-header-letter-spacing': 'var(--type-table-header-letter-spacing)',
  '--type-stat-label-family': 'var(--font-family-sans)',
  '--type-stat-label-size': 'var(--font-size-12)',
  '--type-stat-label-weight': 'var(--font-weight-bold)',
  '--type-stat-label-color': 'var(--color-text-secondary)',
  '--type-stat-label-line-height': 'var(--line-height-normal)',
  '--type-stat-label-letter-spacing': 'var(--tracking-caps)',
  '--type-metric-display-family': 'var(--font-family-sans)',
  // Hero stat values use the 23 step; the role stays separate so metric figures
  // can move independently from page titles even when they share a primitive.
  '--type-metric-display-size': 'var(--font-size-23)',
  '--type-metric-display-weight': 'var(--font-weight-heavy)',
  '--type-metric-display-color': 'var(--color-text-primary)',
  '--type-metric-display-line-height': '1.08',
  '--type-metric-display-letter-spacing': '0',
  '--type-metric-display-compact-size': 'var(--font-size-23)',
  '--type-metric-display-small-size': 'var(--font-size-18)',
  '--type-button-label-family': 'var(--font-family-ui-label)',
  '--type-button-label-size': 'var(--font-size-14)',
  '--type-button-label-weight': 'var(--font-weight-semibold)',
  '--type-button-label-line-height': 'var(--line-height-normal)',
  '--type-button-label-letter-spacing': '0',
  '--type-subpage-tab-family': 'var(--font-family-ui-label)',
  '--type-subpage-tab-size': 'var(--type-body-xl-size)',
  '--type-subpage-tab-weight': 'var(--font-weight-semibold)',
  '--type-subpage-tab-color': 'var(--color-text-primary)',
  '--type-subpage-tab-line-height': 'var(--line-height-none)',
  '--type-subpage-tab-letter-spacing': '0',
  '--type-sidebar-button-label-family': 'var(--type-button-label-family)',
  '--type-sidebar-button-label-size': 'var(--font-size-14)',
  '--type-sidebar-button-label-weight': 'var(--font-weight-semibold)',
  '--type-sidebar-button-label-color': 'var(--color-text-primary)',
  '--type-sidebar-button-label-line-height': 'var(--type-button-label-line-height)',
  '--type-sidebar-button-label-letter-spacing': 'var(--type-button-label-letter-spacing)',
  // Position tokens — single knobs for cross-page positions (private theme specification §3 "Standard
  // positions"). Sizes default to var(--type-<tier>-size) so the tier knob still
  // carries them; re-point a position's own token to detach just that family.
  '--type-money-weight': 'var(--font-weight-semibold)',
  '--type-money-color': 'var(--color-text-primary)',
  '--type-row-description-weight': 'var(--font-weight-medium)',
  '--type-row-description-color': 'var(--color-text-primary)',
  // Income detail breakdown account name — the tertiary text tag that leads each
  // dividend/interest drawer row (ticker/type stay on the neutral text ramp).
  '--type-income-account-color': 'var(--color-text-tertiary)',
  // Secondary row/name lines such as Holdings company names. Kept below section
  // counts and table headers so dense tables do not flatten into one text tier.
  '--type-row-subtext-color': 'var(--color-text-faint)',
  // Hints were too small on the secondary (12px) tier — moved up to the body tier.
  '--type-field-hint-size': 'var(--type-body-size)',
  '--type-field-hint-weight': 'var(--font-weight-regular)',
  '--type-field-hint-color': 'var(--color-text-faint)',
  '--type-field-hint-line-height': 'var(--line-height-normal)',
  '--type-inline-error-size': 'var(--type-secondary-size)',
  '--type-inline-error-weight': 'var(--font-weight-regular)',
  '--type-inline-error-color': 'var(--color-negative)',
  '--type-empty-state-size': 'var(--type-body-size)',
  '--type-empty-state-weight': 'var(--font-weight-regular)',
  '--type-empty-state-color': 'var(--color-text-secondary)',
  '--type-empty-state-title-size': 'var(--type-body-large-size)',
  '--type-empty-state-title-weight': 'var(--font-weight-semibold)',
  '--type-empty-state-title-color': 'var(--color-text-primary)',
  '--type-menu-option-size': 'var(--type-body-size)',
  '--type-menu-option-family': 'var(--font-family-ui-label)',
  '--type-menu-option-weight': 'var(--font-weight-semibold)',
  '--type-menu-option-color': 'var(--color-text-primary)',
  '--type-trigger-label-family': 'var(--font-family-ui-label)',
  '--type-trigger-label-size': 'var(--type-body-size)',
  '--type-trigger-label-weight': 'var(--font-weight-semibold)',
  '--type-trigger-label-color': 'var(--color-text-primary)',
  '--type-topbar-trigger-label-family': 'var(--font-family-ui-label)',
  '--type-topbar-trigger-label-size': 'var(--type-button-label-size)',
  '--type-topbar-trigger-label-weight': 'var(--type-button-label-weight)',
  '--type-topbar-trigger-label-color': 'var(--color-text-primary)',
  '--type-input-size': 'var(--type-body-large-size)',
  '--type-input-weight': 'var(--font-weight-regular)',
  '--type-input-color': 'var(--color-text-primary)',
  '--type-input-compact-size': 'var(--type-body-size)',
  '--type-action-link-size': 'var(--type-body-size)',
  '--type-action-link-weight': 'var(--font-weight-medium)',
  '--type-action-link-color': 'var(--color-accent-primary)',
  '--type-panel-header-link-size': 'var(--type-action-link-size)',
  '--type-panel-header-link-weight': 'var(--font-weight-semibold)',
  '--type-panel-header-link-color': 'var(--type-action-link-color)',
  '--type-chart-toggle-size': 'var(--type-secondary-size)',
  '--type-chart-toggle-weight': 'var(--font-weight-semibold)',
  '--type-chart-toggle-color': 'var(--color-text-primary)',
  '--type-button-label-compact-size': 'var(--type-secondary-size)',
  '--type-badge-family': 'var(--font-family-ui-label)',
  '--type-badge-size': 'var(--font-size-11)',
  '--type-badge-weight': 'var(--font-weight-bold)',
  '--type-badge-color': 'var(--color-text-secondary)',
  '--type-badge-line-height': 'var(--line-height-none)',
  '--type-badge-letter-spacing': 'var(--tracking-caps)',
});

export const breaktwentyTypography = Object.freeze({
  fontFamilies: breaktwentyFontFamilies,
  fontWeights: breaktwentyFontWeights,
  chart: Object.freeze({
    tickFontSize: 12,
    tickFontWeight: breaktwentyFontWeights.regular,
    denseTickFontWeight: breaktwentyFontWeights.semibold,
    axisLabelFontSize: 12,
    iconFontSize: 14,
    pieLabelFontSize: 12,
  }),
});

// Canonical ECharts text-style objects — the ONLY chart tick/axis typography.
// tick = hero/simple charts (Net Worth); denseTick/axisLabel = data-dense charts
// (Holdings income, Cash Flow). Spread these into ECharts options; never inline
// fontSize/fontWeight literals in chart code.
export const breaktwentyChartText = Object.freeze({
  tick: Object.freeze({
    fontFamily: breaktwentyFontFamilies.sans,
    fontSize: breaktwentyTypography.chart.tickFontSize,
    fontWeight: breaktwentyTypography.chart.tickFontWeight,
  }),
  denseTick: Object.freeze({
    fontFamily: breaktwentyFontFamilies.sans,
    fontSize: breaktwentyTypography.chart.tickFontSize,
    fontWeight: breaktwentyTypography.chart.denseTickFontWeight,
  }),
  axisLabel: Object.freeze({
    fontFamily: breaktwentyFontFamilies.sans,
    fontSize: breaktwentyTypography.chart.axisLabelFontSize,
    fontWeight: breaktwentyTypography.chart.denseTickFontWeight,
  }),
});

export function applyBreakTwentyTypography(target = typeof document !== 'undefined' ? document.documentElement : null) {
  if (!target?.style) return;

  Object.entries(breaktwentyTypographyCssVariables).forEach(([name, value]) => {
    target.style.setProperty(name, value);
  });
}
